#!/bin/sh

set -e

export BROKEN=1
export GLUON_AUTOREMOVE=1
export GLUON_DEPRECATED=1
export GLUON_SITEDIR="${GLUON_SITEDIR:-contrib/ci/minimal-site}"
export GLUON_TARGET="$1"
export BUILD_LOG=1

echo "${GLUON_SITEDIR}"
tree "${GLUON_SITEDIR}"

echo "GLUON_AUTOUPDATER_ENABLED: ${GLUON_AUTOUPDATER_ENABLED}"
echo "GLUON_AUTOUPDATER_BRANCH: ${GLUON_AUTOUPDATER_BRANCH}"

make update
make -j2 V=s
